[tool.poetry]
name = "lib2"
version = "0.1.0"
description = ""
authors = ["Timothy Laurent <tlaurent@genedx.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ruff = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
