[tool.poetry]
name = "lib1"
version = "0.1.0"
description = ""
authors = ["Timothy Laurent"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lib2 = { path="../lib2/", develop = true }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
